controller_list:
  - name: fake_ur5_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint
  - name: fake_torso_controller
    type: $(arg fake_execution_type)
    joints:
      - ewellix_lift_top_joint
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_finger_joint1
  - name: fake_arm_torso_controller
    type: $(arg fake_execution_type)
    joints:
      - ewellix_lift_top_joint
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint
initial:  # Define initial robot poses.
  - group: ur5_arm
    pose: arm_default